# Generated by Django 5.2.1 on 2025-08-10 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0002_alter_loanapplication_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('MM', 'Mobile Money'), ('BT', 'Bank Transfer'), ('CC', 'Credit/Debit Card')], max_length=2)),
                ('frequency', models.CharField(choices=[('OT', 'One-time'), ('MN', 'Monthly')], default='OT', max_length=2)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('is_recurring', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loan.loanapplication')),
            ],
        ),
    ]
