# Generated by Django 5.2.1 on 2025-08-09 14:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The public-facing name of this loan product', max_length=50, verbose_name='Loan Name')),
                ('description', models.TextField(verbose_name='Detail Description')),
                ('slug', models.SlugField(help_text='URL indentifier', max_length=60, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Brief summary for cards and listings', max_length=150, verbose_name='Short Description')),
                ('loan_type', models.CharField(choices=[('PL', 'Personal Loan'), ('BL', 'Business Loan'), ('EL', 'Emergency Loan'), ('EDL', 'Education Loan'), ('STL', 'Startup Loan'), ('MDL', 'Medical Loan')], default='PL', max_length=50, verbose_name='Loan Types')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual Percentage Rate', max_digits=12, verbose_name='Interest Rate (%)')),
                ('term_length', models.PositiveSmallIntegerField(verbose_name='Term Length (months)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this loan product currently available?', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('requirements', models.TextField(blank=True, verbose_name='Eligibility Requirements')),
                ('featured', models.BooleanField(default=False, help_text='Show this loan prominently on the homepage', verbose_name='Featured Product')),
                ('icon', models.CharField(default='fa-solid fa-money-bill-wave', help_text="Enter a Font Awesome class name (e.g., 'fa-solid fa-briefcase')", max_length=50)),
            ],
            options={
                'verbose_name': 'Loan Product',
                'verbose_name_plural': 'Loan Products',
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(default='customer@gmail.com', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('APD', 'Approved'), ('RJD', 'Rejected')], default='PD', max_length=50)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('purpose', models.TextField(blank=True, help_text='Why do you need this loan?', verbose_name='Purpose of Loan')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='loan_applications/id_proofs/')),
                ('income_proof', models.FileField(blank=True, null=True, upload_to='loan_applications/income_proofs/')),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-applied_date'],
            },
        ),
    ]
